name: Build and Deploy Sphinx Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r templates/requirements.txt

      - name: Build all cookbooks
        run: |
          if [ -d cookbooks ] && [ "$(find cookbooks -mindepth 1 -maxdepth 1 -type d | wc -l)" -gt 0 ]; then
            for d in cookbooks/*/ ; do
                sphinx-build "$d" "$d/_build/html"
            done
          else
            echo "No cookbooks found. Skipping cookbook build."
          fi

      - name: Build main docs
        run: |
          sphinx-build docs docs/_build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          keep_files: true